# 先运行 docker network create back

version: '3'
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        image: cq-picsearcher-bot
        container_name: cq-picsearcher-bot
        restart: always
        depends_on:
            - server

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        image: go-cqhttp
        container_name: go-cqhttp
        restart: always
        ports:
            - 8080:8080
            - 5700:5700