FROM alpine

WORKDIR /WWW/WWWROOT/

# 下载go-cqhttp
ADD $(curl -s https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest | grep "browser_download_url.*go-cqhttp_linux_amd64.tar.gz" | cut -d '"' -f 4)  /WWW/WWWROOT/

# 解压压缩包
RUN tar -xzvf go-cqhttp_linux_amd64.tar.gz

# 拷贝配置到centos镜像中
COPY ./config.yml /WWW/WWWROOT/

EXPOSE 8080 6700 5600

# 启动容器时执行gq-cqhttp
CMD ./go-cqhttp
